### ISSUE TITLE
Composer does not handle autoloading correct

### ISSUE THREAD

**Issue by akkie** [ray-di/Ray.Di#10]
Hi,

I have found an issue with the installation of Ray.Di under windows. The problem is that composer creates the directory ray/aop with a lower case letter and the directory Ray/Di with an upper case letter at the beginning. This does works on linux due its case sensitive manner, but on windows composer creates only one directory ray due its case insensitive manner.

The problem is that the autoloader references to the directory Ray with an upper case letter. And this doesn't exists under windows. Because the packages are installed in ray/aop and ray/Di.

I think the best would be to let composer create only one directory ray for both packages.

Cheers,
Christian

**Comment by akkie** [comment]
I think that issue has to do with the following composer issue: https://github.com/composer/packagist/issues/186

Maybe you must request the renaming for your packages as the aura team has do it for their packages.

And I think the autoload  part of your composer.json is wrong. Normally the path  "Aura\Di": "vendor/Aura/Di/src/" isn't needed, because the vendor sets its own autoload path. The result in my autoload_namespaces.php is as follows:

'Aura\Di' => array($vendorDir . '/aura/di/src/', $vendorDir . '/Ray/Di/vendor/Aura/Di/src/'),

The first part comes from aura package and the second part comes from your definition, which is wrong as well.

Cheers,
Christian

**Comment by koriym** [comment]
Fixed my part of composer.json  (this was because they had no section before. https://github.com/auraphp/system/issues/15 )

**Comment by koriym** [comment]
Hi Christian,

I don't figure out what is right procedure to ask, any form ?

**Comment by akkie** [comment]
I have opened a request. Please can you confirm it.

Cheers,
Christian

**Comment by koriym** [comment]
Confirmed: its fixed.
