### ISSUE TITLE
 It isn't possible to declare the binding with a leading back slash

### ISSUE THREAD

**Issue by koriym** [ray-di/Ray.Di#11]
**Binding**
- It isn't possible to declare the binding with a leading back slash:

``` php
<?php

// Doesn't work
$this->bind('\model\daos\UserDAO')->to('\model\daos\DbUserDAO');

// Does work
$this->bind('model\daos\UserDAO')->to('\model\daos\DbUserDAO');
```

*this issue was raised by @akkie in issue #6

**Comment by madapaja** [comment]
does this issue mean that needs namespace canonicalization in bind() method?
or, do you think that there are the other right approaches?
