### ISSUE TITLE
ControllerFactoryFilter::getController returns false

### ISSUE THREAD

**Issue by aydot** [ray-di/Ray.Di#113]
ControllerFactoryFilter::getController returns false when trying to use controller method injection

**Comment by koriym** [comment]
hi @aydot 

You mention about this ?
https://github.com/lorenzo/piping-bag/blob/master/src/Routing/Filter/ControllerFactoryFilter.php#L93

Please make the issue at piping-bag. (I can cooperate with @lorenzo. )

**Comment by aydot** [comment]
yes, i keep switching windows back and forth, i didn't realize i posed on yours.

**Comment by koriym** [comment]
;)
