### ISSUE TITLE
Occur warning on Windows Environment

### ISSUE THREAD

**Issue by ritalin** [ray-di/Ray.Di#121]
In http://bearsunday.github.io/manuals/1.0/ja/quick-start.html

Running "php bootstrap/web.php get /hello" has lead to worn messages on windows environment. 

```
Warning: file_put_contents(...\MyVendor.MyPackage/var/tmp/cli-hal-app/__BEAR_AppMeta_AbstractAppMeta-*.php): failed to open stream: Bad file descriptor
 in ...\MyVendor.MyPackage\vendor\ray\compiler\src\DependencySaver.php on line 30

Warning: file_put_contents(...\bear\MyVendor.MyPackage/var/tmp/cli-hal-app/__BEAR_AppMeta_AbstractAppMeta-*.php.meta.php): failed to open stream: Bad file d
escriptor in ...\MyVendor.MyPackage\vendor\ray\compiler\src\DependencySaver.php on line 32

....
```

This is reson that an \* charactor invalid as the path charactor on windows environment.

Currently, It has been circumvented with modifying Ray\Di\Name\ANY declalation to '#' charactor.

**Comment by koriym** [comment]
Hello @ritalin 
Thank you for reporting the issue !

 `#` seems ok to work. But we need explanation. (`*` is more intuitive)
maybe '' is better option if possible like an interface.

Your thought ?

**Comment by ritalin** [comment]
I have no problem if it is enable to avoid the warning.

**Comment by koriym** [comment]
@ritalin Would you check in your Windows ? (I don't have !)
