### ISSUE TITLE
Want to modify property for object configured already

### ISSUE THREAD

**Issue by ritalin** [ray-di/Ray.Di#131]
In each independent Module A and B, I want to modify property for object (dpendency) configured already with another Module C.

Please teaach me best practice this issue.

**Comment by ritalin** [comment]
Using _move_ method of Container class, I have switched annotation for targe object.
This is success.
- Module A

```
protected function configure()
{
    $this->bind(AIntf::class)->to(A::class);
}
```
- Module B

```
protected function configure()
{
    $this->bind(BIntf::class)->to(B::class);
}
```

```
class SomeProvider implements ProviderInterface
{
    public function __construct(AIntf $a, BIntf $b)
    {
        $a->prop = $b;
    }
}
```
- Module C

```
protected function configure()
{
    $this->getContainer()->move(AIntf::class, Name::ANY, AIntf::class, 'Other');
    $this->bind(AIntf::class)->to(SomeProvider::class);
}
```

More any Idea?

**Comment by koriym** [comment]
`AbstractModule::rename()` is available. But undocumented.
https://github.com/ray-di/Ray.Di/blob/fb36510912dcd13a0081277e494d4f1e903f58f5/tests/Fake/FakeRenameModule.php#L9

However I do not encourage to design Module rely other module bindings. Each module should be independent, I think. Found no equivalent function in Guice ?

**Comment by koriym** [comment]
@ritalin issueは（英語で書くのが負担なら）日本語でも大丈夫です！ / `SomeProvider`に`get`インターフェイスないです / サンプルスクリプトはPSR / PHPで一般的な命名にしてただければ  (`AInterface`) さらに読みやすいと思います。
