### ISSUE TITLE
ひとつのインスタンスを複数のインターフェースからアクセスしたい

### ISSUE THREAD

**Issue by ritalin** [ray-di/Ray.Di#132]
```
class C implements A, B { ... }
```

というクラス定義があったとして、

インターフェースAからでもBからでも、同一のインスタンスが取得したい場合、どのようにモジュールを記述するのでしょうか？

google/guiceの場合において、

``` java
this.bind(A.class)->to(C.class)； // インターフェースAでバインドしておき
this.bind(B.class)->toProvider(this.getProvider(A.class)); // インターフェースBからのバインドを追加する
```

のような振る舞いを希望しています。

**Comment by koriym** [comment]
> インターフェースAからでもBからでも、同一のインスタンスが取得したい

`AInterface`を`CProvider`に、`BInterface`を`CProvider`にシングルトンで束縛します。
