### ISSUE TITLE
Assisted Injection と Injection Point

### ISSUE THREAD

**Issue by kilica** [ray-di/Ray.Di#148]
Meetup のときに教えていただいた Assisted Injection / Injection Point について再度教えて下さい。

以下のように、onGet() で $foo を Assisted Injection するときに、$id の値を見て $foo を生成する処理を FooProvider::get() 内で作りたいと考えています。

Injection Point では、

```
$ip->getClass();
$ip->getMethod();
$ip->getParameter();
$ip->getQualifiers();
```

のメソッドが用意されていますが、"id" という引数の名前は取得できるのですが、$id の値の取得の仕方が分かりませんでした。どのように取得できるか教えてください m(__)m

`src/Resource/Page/Index`

```
class Index extends ResourceObject
{
    /**
     * @Assisted("foo")
     */
    public function onGet($id, FooInterface $foo)
    {
        return $this;
    }
}
```

`src/Provide/FooProvider.php`

```
class FooProvider implements ProviderInterface
{
    /**
     * @var InjectionPointInterface
     */
    private $ip;

    public function __construct(InjectionPointInterface $ip)
    {
        $this->ip = $ip;
    }

    public function get()
    {
        $ip = $this->ip;

        // $id の値をどうにか取得して Foo を生成したい。
        $foo = new Foo($id);
        return $foo;
    }
}
```

**Comment by koriym** [comment]
@kilica すいません、これ勘違いしていました！`InjectionPoint`はあくまでも注入先の情報でスタティックな値なのでメソッド実行時の変数は渡されません。

**Comment by kilica** [comment]
そっか、残念ですが、ご回答ありがとうございます ^ ^

**Comment by koriym** [comment]
#149 作りました。トライしてみます。

**Comment by koriym** [comment]
https://github.com/ray-di/Ray.Di/pull/150

**Comment by koriym** [comment]
https://github.com/ray-di/Ray.Di/pull/150/commits/11b866be448863349aa9c10c15f03815618889e0#diff-4ebfa7266838b754c3e48ccf6adb6845R21

@kilica こんな感じですがどうでしょうか

**Comment by kilica** [comment]
わ、すごいです。これならやれそうです。
試してみます！　すごい楽しみ。

**Comment by koriym** [comment]
@kilica テスターになってもらっていいですか。問題ないようならリリースします。

**Comment by koriym** [comment]
マニュアルも追加して、ついでに日本語マニュアルも英語版に合わせて変えました。
こちらも目を通してもらったら助かります！

**Comment by kilica** [comment]
http://bearsunday.github.io/manuals/1.0/ja/quick-api.html
の bear/skeleton に組み込んで使おうとしましたら、以下のようなエラーが出ました。

> Catchable fatal error: Argument 1 passed to Ray\Di\Container::merge() must be an instance of Ray\Di\Container, null given, called in 
> /Users/kilica/Dropbox/htdocs/Kilica.Task/vendor/ray/di/src/AbstractModule.php on line 67 and defined in /Users/kilica/Dropbox/htdocs/Kilica.Task/vendor/ray/di/src/Container.php on line 134

当てずっぽうですが、

```
https://github.com/ray-di/Ray.Di/pull/150/commits/7cac11e9b59d11d29c04ad99813a76377243539b
```

の修正を戻して、 `AbstractModule::getContainer()` 内で `$this->activate()` するようにしてみたところ、正常に動作します。

**Comment by koriym** [comment]
revertのPRしてもらっていいでしょうか

**Comment by kilica** [comment]
了解です、といいたいのですが、pull request に対して pull request って送れるのでしょうか？
Fork しても pull request はくっついてこないようですし、Github のヘルプを探してもそれらしいページが見つかりませんでした >_<

どこかやり方の書いてあるページが有りましたら、お手数ですが教えていただけますでしょうか m(__)m

**Comment by koriym** [comment]
PRしてるbranchに対してPRすればどうでしょうか。

**Comment by kilica** [comment]
ありがとうございます。
PR している branch (2.x)ですと、まだPR分の変更が反映されていませんので、revert もできないのではないでしょうか？

**Comment by koriym** [comment]
今のPRのbranchに対してです。ちょっとややこしくなってきたので今回私の方でしますね！

**Comment by kilica** [comment]
お手数おかけします m(__)m

それ以外の、Assisted Injection と MethodInvocationProvider を使った DI は、今のところうまく動いています！

**Comment by koriym** [comment]
mergeしてコントリビューターのリストも更新しました！
http://bearsunday.github.io/contributors.html

**Comment by koriym** [comment]
2.4.0 としてリリースしました
https://github.com/ray-di/Ray.Di/releases/tag/2.4.0
