### ISSUE TITLE
Exception name

### ISSUE THREAD

**Issue by koriym** [ray-di/Ray.Di#16]
I would like to hear  from someone who is familiar with Guice about Ray.Di's exception names.
@akkie, If you have any suggestion, please give us a PR,

Cheers.

**Comment by akkie** [comment]
Yea, this is on my to-do list like some other code cleaning improvements.
- Fix exception names (NotBinded => NotBoundException, ...)
- Better exception message for method Injetor::jitBinding(Binding not found)
- Fix some spelling errors (binded => bound)
- Fix CamelCase issues
- Fix PHPDoc issues

But as noted in another post, in my spare free time I'm very busy with https://github.com/mohiva/elixir at the moment. And at the weekends I would spend time with my two little children and try to be a good father and husband. (o;

Cheers,
Christian

**Comment by koriym** [comment]
Thanks @akkie. I fix which you mentioned here.

Children always first, off course !
have a great weekend.

**Comment by akkie** [comment]
@koriym Which IDE do you use? Have you ever looked at PHPStorm. A very excellent IDE with a good spell checker engine, with good PHPDoc inspections and many, many more.

I will send you a pull request with all the fixed issues PHPStorm has detected in the Injector.php file.

Cheers

**Comment by koriym** [comment]
@akkie Thanks for the info. Eclipse with PDT for many years. Have you compared with it ? ( I switched to turn "on" checker :-0 )

**Comment by akkie** [comment]
I changed 2 years ago from Eclipse PDT to PHPStorm and the two can not be compared. PDT is also just a scaled version, with a minimalist feature set, of Zend Studio. Jetbrains has a [EAP program](http://confluence.jetbrains.net/display/WI/Web+IDE+EAP;jsessionid=45717ECB759E77F382CE96DB232A8028) with a 30-day time-limited license for every new build. But they also have an [open source license](http://www.jetbrains.com/phpstorm/buy/buy.jsp#openSource). I have the open source license for the Mohiva project. So every user who commits code to the project can use this license for free. This IDE is very popular in Europe and I can thoroughly recommend it.

**Comment by koriym** [comment]
@akkie thank you for the detail info. I  must try it !
