### ISSUE TITLE
Constructor with string and array

### ISSUE THREAD

**Issue by raph007** [ray-di/Ray.Di#161]
Hi,

Let's say I have class 'MyClass' with this constructor:

`public function __construct(string $par1, array $par2, SomeOtherClass $someOtherObject)`

how  "configure" method in my DI module would look like (version without annotations)?

**Comment by koriym** [comment]
`toConstrocur` bindings is ideal for this case (without annotations)
I think this PDO example on README (I update 10min ago!)  helps your case.
 
![image](https://user-images.githubusercontent.com/529021/28491691-9a787bac-6f30-11e7-93d0-a5e2d815e0c6.png)

**Comment by koriym** [comment]
The previous code is for ray/di ^2.5.3 (release 10min ago)

for older version (and also latest `2.5.3`), You can code as following

```php
protected function configure()
{       
    $this->bind(\PDO::class)->toConstructor(
        \PDO::class,
        'pdo=pdo_dsn,username=pdo_username,password=pdo_password' // string
    )->in(Scope::SINGLETON);
    $this->bind()->annotatedWith('pdo_dsn')->toInstance($dsn);
    $this->bind()->annotatedWith('pdo_username')->toInstance($username);
    $this->bind()->annotatedWith('pdo_password')->toInstance($password);
}
```

**Comment by raph007** [comment]
I came up with something like this (before your reply):

```php
protected function configure()
    {
        $this->install(new SomeOtherClassModule());

        $this->bind(MyClass::class)
            ->toInstance(
                new MyClass(
                    'sometuff,
                    ['a', 'b'],
                    $this->getContainer()->getInstance(SomeOtherClass::class,'')
                )
            );
    }
```

but let my try with your example (documentation is now way clearer BTW :)).

**Comment by koriym** [comment]
For your code, this code should work.

```php
protected function configure()
{       
    $this->bind(MyClass::class)->toConstructor(
        MyClass::class,
        'par1=par1_name,par2=par2_name' 
    );
    $this->bind()->annotatedWith('par1_name')->toInstance($par1);
    $this->bind()->annotatedWith('par2_name')->toInstance($par2);
}
```

**Comment by koriym** [comment]
Instance binding is like a final method when you can not bind other method.
 
`instance` was serialized. = you can't use it as singleton. Also you can't use AOP for it.  `instance binding` should be use only primitive type or simple value object. Not for service class.

**Comment by koriym** [comment]
Also `Provider` binding works in your case. See the example here.

https://github.com/bearsunday/BEAR.Package/blob/1.x/src/Context/Provider/ProdCacheProvider.php

You may (or may note) annotate your provider class (=factory class), But you don't need to annotate your original class. Provider can receive dependencies (SomeOtherClass). 

Singleton is available. But still AOP is not possible.

**Comment by raph007** [comment]
This solution is ok for me:

```php
protected function configure()
{       
    $this->bind(MyClass::class)->toConstructor(
        MyClass::class,
        [
        	'par1' => 'par1_name',
        	'par2' => 'par2_name'
        ]
    );
    $this->bind()->annotatedWith('par1_name')->toInstance($par1);
    $this->bind()->annotatedWith('par2_name')->toInstance($par2);
}
```

Thank you for quick reply. Very good work with this lib.

**Comment by koriym** [comment]
It's not very very popular lib. But I believe it is one of the most powerful and fastest lib in this category. Thank you for the try Ray.Di. Feel free to ask anything ! :) 

Tip) We don't need to touch container directly unlike other "DI container". It is a "injector". We just declare bindings then Injector create object graph with the bindings.

**Comment by raph007** [comment]
I was looking some DI container for our project in CakePHP and found it because of Lorenzo's plugin for Cake. 

I believe it could be more popular if guys from CakePHP mentioned it on Cake doc's as good solution for DI.

**Comment by koriym** [comment]
Yes, He use very seriously on his project not only as Dependency Injector but also AOP functions.
