### ISSUE TITLE
Why do you use assert in production code?

### ISSUE THREAD

**Issue by route33** [ray-di/Ray.Di#282]
According to PHP documentation, `assert` shall be used only on tests, not production code https://www.php.net/manual/en/function.assert.php

Why do you use `assert` in production code?

**Comment by koriym** [comment]
I am not using `assert` for testing, but as an alternative to inline @var to tell static analysis tools like phpstan or psalm more about variable types.

https://phpstan.org/writing-php-code/phpdocs-basics#inline-%40var
https://phpstan.org/writing-php-code/narrowing-types
