### ISSUE TITLE
APC=on時にgetInstance()でエラー

### ISSUE THREAD

**Issue by madapaja** [ray-di/Ray.Di#3]
仕様なのかも知れませんが、一つのPHPファイルにクラスを記述すると、エラーが発生します。
（APCがOFFの場合にはエラーは発生しません。）

```
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /test/vendor/Ray/Di/src/Ray/Di/ApcConfig.php on line 40
```

ApcConfigでのファイルの読み込み時に無限ループに陥ってしまっているように見えます。

エラーになるコードと、発生するエラーメッセージ：
https://gist.github.com/3127484

なお、同一のプログラムでも、下記のようにクラスごとにファイルを分割するとエラーにはなりません。
https://gist.github.com/3127506

**Comment by koriym** [comment]
確認しました。
CLI / Webでも変わりなく、Xdebugも関係ありませんでした。

該当箇所はarray_walkと"array passed by reference"を利用しています。
関連個所（？）

Bug #61730  Segfault from array_walk modifying an array passed by reference
http://php.net/manual/en/function.array-walk.php

原因は分かりませんが、array_walk が先に進んでないようににも思えます。
対応はクラスを別にすることと、コーディング案内のようなページで注意喚起します。

一旦閉じます。
