### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by craigjbass** [ray-di/Ray.Di#43]
Following Injektor's vein of performance improvements
- Pre-compiled factory-pattern classes that do the heavy-lifting instantiation of objects.
- Deprecate use of memcached as a performance improver in favour of this method.

Potential output from compiler

``` php
/**
 * Autogenerated. Do not modify.
 **/
class \ApplicationNamespace\Ray\Di\Compiled\SomeModelFactory extends SomeFactoryAbstract {

   /* @var InjectionMethod[] */
   private $injectionMethods;

   /* @var string[] */
   private $postConstructMethods = [ 'onInit' ];

   /**
    * @return SomeModel
    */
   public function instantiate() {
       //Define injections
       $table = $this->getInstanceOf( 'SomeZendTable' ); 
       $this->injectionMethods[] = new InjectionMethod( 'injectTables', [ $table ] );

       $instance = new SomeModel();

       //handle injections
       $this->inject();

       //run postconstruct methods
       $this->postConstruct();

       $this->isSingleton( 'SomeModel', $instance );

       return $instance;
   }

}

```

**Comment by koriym** [comment]
@craigjbass thank you for the paying attention !
I believe code generation programing like as you mention here solve more problem and the way to go for the performance. (through the experience of AOP generated code)

But before we discuss about more technical things, Would you let us know why you think this way is better than object serialization ?  

Here are my thoughts of the benefit for injected-dependency object serialization.
- unserialize($injectedObject);  Fastest way to get dependency-injected object.
- We can examine what is injected _before_ we run.
- Visualization of injection may become easier. (not ready yet but i want)

**Comment by craigjbass** [comment]
I am assuming by serialization you mean serialize-once either precompiled or on the first web request (memcache the instances) unserialize-many times afterwards.

I don't like this particular technique as it requires carefully designing your objects to handle their life-cycle with care.
E.g. __construct may define a constant, do something to php state etc.

This is fine for project created classes, but if you want to inject 3rd party libraries you would need to create wrappers for all of them.

**Comment by koriym** [comment]
..your assumption is correct. thanks.

> I don't like this particular technique as it requires carefully designing your objects to handle their life-cycle with care.

I see. Thank you for your clarification.

By through my experience of BEAR.Sunday framework development, I think we can handle 3rd party libraries with little care (like using Provider), But I also don't think object serialization is only one answer for all problem. I think your suggestion seems interesting.

**Comment by koriym** [comment]
> $table = $this->getInstanceOf( 'SomeZendTable' ); 
> $this->injectionMethods[] = new InjectionMethod( 'injectTables', [ $table ] );

I can guess how it works that dependency creation and injection in this simple case. 
But what about in another more complex case ? Dependencies can be an object, They may take another dependencies, circular references ...

**Comment by craigjbass** [comment]
I don't think the framework currently handles circular references (I may be wrong, I avoid them on purpose!)

Personally I would like to see a clean solution to the problem without performance hits. Currently we're at the stage of clean solution - but with performance hits. I am using in production because I can offset to performance hit with time to production gains. 

I am up for discussing potential solutions to the performance issue.

I think a first step may be introducing a simple public API that exposes the reflection style structure in a pure core manner to glue classes together, in terms of methods to call...

**Comment by koriym** [comment]
> I don't think the framework currently handles circular references (I may be wrong, I avoid them on purpose!)

"circular references" - we need it for dependency object as singleton ?

I think more discussion with generated code sample makes things clear.

**Comment by koriym** [comment]
> I think a first step may be introducing a simple public API that exposes the reflection style structure in a pure core manner to glue classes together, in terms of methods to call...

sounds nice.  :+1: 

I also think the _potential output_ code.

``` php
class SomeModelFactory extends SomeFactoryAbstract {

    private $container;

    public function __construct(\Aura\Di\ContainterInterface $container)
    {
        $this->container = $container;
    }

    /* @var InjectionMethod[] */
    private $injectionMethods;

    /* @var string[] */
    private $postConstructMethods = [ 'onInit' ];

    /* @var string[] */
    private $preDestroyMethods = [ 'onEnd' ];

    /**
     * @return SomeModel
     */
    public function instantiate() {

        // prepare constructor dependencies
        $constructorParams = [
            'some_scalar_val',
            new SomeClassHasNoConstructorParams,
            $this->container->get('SomeSingletonObject')
        ];

        // prepare setter dependencies
        $setter = [
            'setterMethodName' => [
                'some_scalarar_val',
                new SomeClassHasNoConstructorParams,
                $this->container->get('SomeSingletonObject')
            ],
            'setterMethodName2' => [
                1
            ]
        ];
        // instantiation
        $instance = call_user_func_array(
            [new \ReflectionClass('SomeModel'), 'newInstance'],
            $constructorParams
        );
        // setter injection
        foreach ($setter as $method => $value) {
            call_user_func_array([$instance, $method], $value);
        }
        // @PostConstruct
        $this->postConstruct($this->postConstructMethods);
       // @PreDestroy
        register_shutdown_function(
            function(){
               $this->preDestroy($this->preDestroyMethods);
            }
        );
        return $instance;
    }
}
```

**Comment by craigjbass** [comment]
I like this :+1: 

It allows an experienced developer to construct his own factory methods that will be used by the DI weaver.

``` php

 /**
     * Return bound object or inject info
     *
     * @param $class
     *
     * @return array|object
     * @throws Exception\NotReadable
     */
    private function getBound($class)
    {
        $class = $this->removeLeadingBackSlash($class);

        if( class_exists( $class.'DiFactory' ) ) {
           return $this->getUsingFactory( $class.'DiFactory' );
        } 

        // is interface ?
        try {
            $refClass = new ReflectionClass($class);
            $isInterface = $refClass->isInterface();
            $isInstantiable = $refClass->isInstantiable();
        } catch (ReflectionException $e) {
            throw new Exception\NotReadable($class);
        }

        list($config, $setter, $definition) = $this->config->fetch($class);
        $interfaceClass = $isSingleton = false;
        if ($isInterface) {
            $bound = $this->getBoundClass($this->module->bindings, $definition, $class);
            if (is_object($bound)) {
                return $bound;
            }
            list($class, $isSingleton, $interfaceClass) = $bound;
            list($config, $setter, $definition) = $this->config->fetch($class);
        } elseif ($isInstantiable) {
            try {
                $bound = $this->getBoundClass($this->module->bindings, $definition, $class);
                if (is_object($bound)) {
                    return $bound;
                }
            } catch (NotBound $e) {

            }
        }
        $hasDirectBinding = isset($this->module->bindings[$class]);
        /** @var $definition Definition */
        if ($definition->hasDefinition() || $hasDirectBinding) {
            list($config, $setter) = $this->bindModule($setter, $definition);
        }

        return [$class, $isSingleton, $interfaceClass, $config, $setter, $definition];
    }

```

**Comment by craigjbass** [comment]
Further to this, hardcoding the namespace is probably bad. 
This is just to show the logic flow, rather than actual implementation. This will handle singletons in the existing way using the Aura container one stack call up.

I think that a compiled "module" should contain the configuration e.g. "SomeModel" is always defined as being created by this factory. 

``` php
class CompiledCore extends Ray\Di\AbstractModule {

    public function configure()
    {
        $this->bind( 'SomeModel' )->toFactory( 'SomeModelFactory' );
    }

} 


```

**Comment by craigjbass** [comment]
I've made changes to your potential compiled factory example. 
Particularly this allows fallback to reflection if a factory has not been compiled. This is done by using Ray\Di instead of the Aura container directly. 

Ray would automagically skip the CPU heavy sections of Ray\Di call stack using the code example above, making it still fine to call Ray, and maintain some dynamic loading if needed.

There's also some incomplete ideas in here!

``` php

class SomeModelFactory extends SomeFactoryAbstract {

    private $injector;

    const CLASS_NAME = "SomeModel";

    public function __construct(\Ray\Di\Injector $injector)
    {
        /*
         If this was in the parent class one could make the assumption that this constructor
         *always* needs ONLY the ray injector, thus allowing us to skip over the problem. 
         Another would to make this a basic setter. 
         But I don't think we should introduce any dynamicness into these factories!
         */
        $this->injector = $injector; 
    }

    /* @var InjectionMethod[] */
    private $injectionMethods;

    /* @var string[] */
    private $postConstructMethods = [ 'onInit' ];

    /* @var string[] */
    private $preDestroyMethods = [ 'onEnd' ];

    /**
     * @return SomeModel
     */
    public function instantiate() {

        // prepare constructor dependencies
        $constructorParams = [
            'some_scalar_val',
            new SomeClassHasNoConstructorParams,
//What if SomeSingletonObject has not been set on the container yet or has no way of being statically weaved?
//Calling Ray instead here is potentially better.
            $this->injector->getInstance('SomeSingletonObject') 
        ];

        //Above could be abstracted like:
        //$constructorParams = $this->createConstructorParams( new InjectionMethod( ... ) );

         $this->injectionMethods[ 'setterMethodName' ] = new InjectionMethod( [ 
             'some_scalar_value', 
             new SomeClassHasNoConstructorOrSpecialTreatment, //I like the optimization that can be made here for simple objects!
             new InjectionClass( 'SomeSingletonObject' )
        ] ); 

       $this->injectionMethods[ 'setterMethodName2' ] = new InjectionMethod( [ 1 ] );

        // instantiation (TODO could be abstracted?)
        $instance = (new ReflectionClass('SomeModel'))->newInstanceArgs( $constructorParams );

        // setter injection
        $this->processInjectionMethods();
        // @PostConstruct
        $this->postConstruct($this->postConstructMethods);
       // @PreDestroy
        register_shutdown_function(
            function(){
               $this->preDestroy($this->preDestroyMethods);
            }
        );
        //TODO: A lot more of the above could be abstracted into the parent

        return $instance;
    }
}

```

**Comment by koriym** [comment]
> $this->bind( 'SomeModel' )->toFactory( 'SomeModelFactory' );

This seems same as `toProvider` binding. What's the deference ?

**Comment by koriym** [comment]
> //What if SomeSingletonObject has not been set on the container yet or has no way of being statically weaved?
> //Calling Ray instead here is potentially better.

yes, that is better.

**Comment by craigjbass** [comment]
> This seems same as toProvider binding. What's the deference ?

I think my thinking is that potentially it may diverge from toProvider in the future. The AbstractFactory may never implement the same interface as a provider is expected to. 

Also this specifically says "Do not weave this object, aside from providing known dependency of Ray\Di\Injector to the constructor." With the toProvider there is more logic handling the detection of whether it specifically needs dynamic weaving.

**Comment by koriym** [comment]
I don't 100% get what you mean, Can you enlarge a little on this?

**Comment by craigjbass** [comment]
->toProvider performs Ray\Di\Injector dynamic weaving to instantiate a new provider object.

->toFactory would perform a statically defined weave of AbstractFactory, not a dynamic one.
Otherwise we may end up with things like AbstractFactoryFactory

This is what we want for concrete Factory instances... to be statically weaved.

Two choices here:
- put all that logic in ->toProvider and perform a $class instanceof AbstractFactory check
- or make it inherently clear that it's a factory, not a dynamic provider. (toFactory)

**Comment by koriym** [comment]
`toProvider` can solve dynamic dependency resolution using injector.
`toFactory` design to solve more  static dependency resolution without injector.

Make sense ?

**Comment by craigjbass** [comment]
Yep! That's the idea.

**Comment by koriym** [comment]
I now understand :) thanks.

**Comment by craigjbass** [comment]
Do you think this is something we could work together to achieve, I'm happy to put some of my time in to make this a reality.

How would you design it, you have a deeper understanding of Ray.Di's intricacies

**Comment by koriym** [comment]
@craigjbass Thanks your offer. 

Even I personally don't need this functionality now, I'm happy we can discuss and work together to achieve for this.

**Comment by koriym** [comment]
- improve generated code
- design for the integration with current Injector class

I think I need this first.

**Comment by craigjbass** [comment]
I propose that Ray.Di compiles a concrete AbstractModule, which has been modified to store details of "toFactory" bindings.

The \Ray\Di\Injector::getInstance will call a method _before_ getBound that checks if there is a valid factory available, and if there is instantiate and call that. I believe this should be handled by a separate StaticWeave class.

e.g. 

``` php
    /**
     * {@inheritdoc}
     */
    public function getInstance($class)
    {
        if( $this->staticWeaver->factoryAvailable($class) ) { 
            return $this->staticWeaver->getFactory($class)->get();
        } 

        $bound = $this->getBound($class);

        // return singleton bound object if exists
        if (is_object($bound)) {
            return $bound;
        }

...

```

Do you think this is a sensible approach?

Once we have this in place, we can begin discussing how the compiler will work, however this doesn't need to be efficient :)

**Comment by koriym** [comment]
> The \Ray\Di\Injector::getInstance will call a method before getBound that checks if there is a valid factory available, and if there is instantiate and call that. I believe this should be handled by a separate StaticWeave class.

Yes, I do. I agreed this approach. 

Some minor correction here..
- `Weaver` sounds they have some relation with AOP paradigm ? what about `factoryCompiler` or `providerCompiler`  (or other). `Compiler` already used for class geration for AOP. 
- Just not violating the Law of Demeter...

``` php
if ($this->factoryCompiler->isFactoryAvailable($class)) { 
    return $this->factoryCompiler->geInstance($class);
} 
```

I still wonder the possibility of integration of `toProvider()` and `toFactory()` (no `toFactory()`) Suppose injector can detect "100% static binding" or "dynaming injector binding". We don't need to distinct binding (It become injector's job) Off course we can work for it lator if it works. What do you think ?

**Comment by craigjbass** [comment]
- Okay, how about `StaticInjector` as this is exactly what it is --- an `injector` that only works with statically compiled injections.

agreed:

``` php
if ($this->staticInjector->isFactoryAvailable($class)) { 
    return $this->staticInjector->getInstance($class);
} 
```

I do still think this, but I think the important difference is that the `AbstractFactory` concrete classes will _never_ be dynamically instantiated. i.e. no support for @Inject, @Scope, etc tags in their class definition. This is an important distinction that means we can provide a performance speed-up without having to do things like AppleFactoryFactory :). 

Indeed we _could_ do a dynamic type check e.g. `$factory instanceof AbstractFactory` but I think it's better to make the distinction to a potential API user... They may believe the use of `toProvider` allows for dynamic injection, but for `AbstractFactory` it does not.

**Comment by craigjbass** [comment]
I think the final point is really highlighted by http://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by koriym** [comment]
one conformation:
Are `AbstractFactory concrete classes` generated classes code ?

**Comment by craigjbass** [comment]
Yep

**Comment by koriym** [comment]
I think the superb point of biding DSL of Guice / Ray is that it's completely agnostic about techniques how actually object is created.  Configuration and its implementation are well separated. We can retrieve _object_ without knowing what's going under hood.

In that point of view, _with_ or _without_ new static injector, configuration should be same ?
Optimization is the concern for object creation , not the concern for object design (=binding DSL)

**Comment by koriym** [comment]
@craigjbass That's the way of thinking in principle. It's not saying your `toFactory()` idea doesn't work. Absolutely no.

**Comment by craigjbass** [comment]
Yes I like the fluid interface Guice/Ray provides... 

We can have a marker interface like the following (or similar)

``` php
interface NoDynamicInjection {}
```

**Comment by koriym** [comment]
Also I prefer annotation to "annotate".

**Comment by craigjbass** [comment]
Yes I think that from an end-user perspective annotations are the way to go (one of the reasons I like Guice/Ray)

From a performance perspective, we want to avoid Reflection/Annotation reading for statically compiled `ProviderInterface` classes which are used by the `StaticInjector`. 

If we use `toProvider` as a way of binding "Static" factories to Ray.Di, we will need some sort of marker interface that specifies that we want no reflection to go on.

**Comment by craigjbass** [comment]
I do still prefer `toFactory` method as it requires less run-time checking to occur inside the `StaticInjector`, instead we push this to the compiler.

**Comment by koriym** [comment]
I think there are two stage for injection 
- injector compile / all analysis (annotations and bindings) and code generation are done.
- runtime injection

The injector compilation can be cached and be re-usable. So we don't need to worry about for the time consuming for annotation or reflection ?

**Comment by craigjbass** [comment]
If we can avoid any overhead by eliminating this at compile time, surely this would be far more scalable. 

Large applications would benefit if more memcached space was allocated to application specific data not back-end frameworks for low level speedups. (Although I would agree it's not uncommon).  There is also the issue in ensuring consistency between deploys, etc. this requires md5'ing the file contents (disk I/O overhead)

**Comment by koriym** [comment]
@craigjbass Suppose we have minor difference with how to think about configuration, I buy your passion about optimization !

**Comment by koriym** [comment]
@craigjbass  Would you check #55 ? It enables to optimize injection using injection logger (track dependency injection) I think if it works fine, We can create code-creation performance boost on next step.

**Comment by koriym** [comment]
move to #56
