### ISSUE TITLE
bindInterceptor()したクラスを使うときに、毎回/tmpにクラスファイルが作られてしまう

### ISSUE THREAD

**Issue by yukikaoru** [ray-di/Ray.Di#44]
インターセプターがバインドされたクラスが一時ファイルとしてテンポラリディレクトリに作成されるのですが、Injector#getInstance()する度に作成されてしまい困っています。

テストで実装したソースはこちらです。
https://github.com/vectorxenon/Ray.Di-aop-test

main.phpを実行すると次のようなファイルが作成されます。

```
$ ls /tmp/*.php
/tmp/YukiServiceFooServiceRay00000000086d911800000000331f3cbbAop.php
/tmp/YukiServiceFooServiceRay00000000086d917f00000000331f3cbbAop.php
```

何か設定方法/使い方がおかしいのでしょうか？

**Comment by koriym** [comment]
これはCompilerクラスがクラス名の決定にobject hashを使ってるのが原因です。使い方に問題はありません。

$bindをシリアライズすれば良いような感じがしますが...

**Comment by koriym** [comment]
https://github.com/koriym/Ray.Aop/issues/20 に移動
