### ISSUE TITLE
constructorInject does not handle toProvider bindings correctly

### ISSUE THREAD

**Issue by craigjbass** [ray-di/Ray.Di#48]
``` php

<?php
class Core extends Ray\Di\AbstractModule {

    public function configure()
    {
        $this->bind( 'Zend_Db_Adapter_Abstract' )
            ->toProvider( '\Devls\Db\DiProvider' );
    }

} 

```

``` php

<?php
namespace Devls\Db;

class DiProvider implements \Ray\Di\ProviderInterface  {

    /**
     * @return \Zend_Db_Adapter_Abstract
     */
    public function get()
    {
        return \Devls_Db_ConnectionManager::getCentralConnection();
    }

} 

```

``` php
<?php
use Ray\Di\Di\Inject;
use Ray\Di\Di\PostConstruct;
use Ray\Di\Di\Scope;

/**
 * @Scope("Singleton")
 */
abstract class Core_Table_Base extends Zend_Db_Table_Abstract {

    public function __construct( \Zend_Db_Adapter_Abstract $db )
    {
        parent::__construct( $db );
    }

}


```

Error occurs: 
Valid interface is not found. (array ?) Injection requested at argument #0 $config in Zend_Db_Adapter_Abstract constructor.

It's trying to inject to the Zend_Db_Adapter_Abstract constructor, which means that it has ignored the existence of the provider.

**Comment by craigjbass** [comment]
I tried fixing this, but the particular section uses a lot of references, making it very hard to understand.

**Comment by koriym** [comment]
@craigjbass thanks for the reporting.
Would you mind prepare test case branch for this failure ?

**Comment by craigjbass** [comment]
I think the bug is related to toProvider bound to an abstract class, not with constructors. I may be wrong.

->bind("SomeAbstractClass")->toProvider( 'SomeAbstractClassProvider' );

**Comment by koriym** [comment]
@craigjbass thanks for the commit. I will check it with your assumption !
