### ISSUE TITLE
Requesting an interface with Injector::getInstance() should return the bound implementation and not a fatal error

### ISSUE THREAD

**Issue by akkie** [ray-di/Ray.Di#5]
Hi,

at this time the method Injector::getInstance() ends in a fatal error if an interface name is given. Instead it should return the bound instance to this interface.

Cheers,
Christian

**Comment by akkie** [comment]
Hi koriym,

this bug isn't fixed. If I try to request an interface, which should be the standard usage for a DIC, then I get an undefined index error in vendor/ray/di/src/Ray/Di/Injector.php on line 218.

Cheers,
Christian

**Comment by koriym** [comment]
The code around L.218 is too rough, However It will be good if I have your test code.
Would you mind to pull-request the test code?

**Comment by akkie** [comment]
I'm very busy at the moment. Maybe at the weekend I can provide a test case for this issue.

Cheers,
Christian

**Comment by koriym** [comment]
@akkie No problem, no rush !

**Comment by akkie** [comment]
I think I have found the issue. The problem is the leading backslash.

This works:

```
model\repositories\UserAccountRepository
```

This doesn't work:

```
\model\repositories\UserAccountRepository
```

Note: UserAccountRepository is an interface. The JIT binding doesn't has this problem. It works with leading and without leading backslash.

**Comment by koriym** [comment]
@akkie thanks for the info.
