### ISSUE TITLE
preDestroy notification causes memory leak

### ISSUE THREAD

**Issue by MugeSo** [ray-di/Ray.Di#54]
Objects having `@preDestory` notification are kept in memory until end of request execution because they are stored in `$preDestroyObjects` property of `Injector` class. 

This is not a problem if the object is a singleton.
However, when the object is not a singleton, the behavior means memory leak.

**Comment by MugeSo** [comment]
refs http://php.net/weakref

**Comment by MugeSo** [comment]
もし、これを仕様として許容するならば、マニュアルなどでは注意書きが必要になる事柄かと思います。

**Comment by craigjbass** [comment]
:+1: for weakref. There isn't really any other way.

Detect weakref availability and use it if possible?

**Comment by koriym** [comment]
I'm curious to see the PR.

**Comment by koriym** [comment]
It seems there are not much chance to use `@preDestory` in most case. I discourage to use this (use `__destruct` instead). I will remove this feature on next major release.

Feel free to re-open this issue if you want to provide further information.
