### ISSUE TITLE
DI Compiler Injection

### ISSUE THREAD

**Issue by koriym** [ray-di/Ray.Di#55]
``` php
//  compile injection
$injector = Injector::create([new DiaryModule]);
$diCompiler = new DiCompiler($injector, new CompileLogger(new Logger()));
$diCompiler->compile('Ray\Di\DiaryInterface');

// run-time injection
 $instance = $diCompiler->getInstance('Ray\Di\DiaryInterface');
```

`$DiCompiler->compile('Ray\Di\DiaryInterface');` tracks all dependency injection in `Injector` then save as injection log.  `DI compiler` can inject dependencies with it but without`Module` (binding information) . It is run-time injection. It save memory usage and boost the performance without object caching.

**Limitation**
- `toInsntace` binding can't take object parameter (because it can't track instance creation)
- AOP is ~~not currently~~ supported.
- `@PostConstruction` is ~~not _currently_~~ supported.
- `@PreDestroy` is not _currently_ supported.

**Comment by koriym** [comment]
A experimental implementation is here 399d4eff5ac475636ca8ac471357f656bc46e28c
`DiCompiler` Test is https://github.com/koriym/Ray.Di/blob/feature/di-compiler/tests/DiCompilerTest.php

**Comment by craigjbass** [comment]
I'm trying to understand, how/in what format does the compiler store the compiled information for use on the next web request?

**Comment by koriym** [comment]
`CompileLogger::instanceContainer` holds collection (array)`Ray\Di\DependencyFactory` objects which are universal factory objects holds all necessary (but minimum) data to re-produce instance on next request (runtime). It holds `class` name, constructor arguments (`args`) and setter method and setter arguments (`setters`)

See the real data belows, It starts from the bottom. `Diary` takes 3 arguments, `Db` First argument is `InstanceRef` object and points `000000006cb064d90000000117a0144d` index. Then you take `000000006cb064d90000000117a0144d` indexed object, which is `Ray\Di\DependencyFactory` object and class name is `Log`. This time there is no constructor injection or setter injection, then it can create new instance. Done ! The first argument is successfully taken and continue to second.

If an other dependency points same object (singleton) It point same index. Object is not re-created.

**Summary**
`CompileLogger::instanceContainer` holds collections either **universal factory** or **instance reference**. I thought this can be a minimum set of data of dependency injection. These logged data doesn't include any real dependency object. This can be cached to use on the next web request.

In real usage, `DiCompiler` can be cached and can be used without original injector or binding.

``` php
protected $instanceContainer =>
  array(6) {
    '000000006cb064d90000000117a0144d' =>
    class Ray\Di\DependencyFactory#177 (7) {
      public $hash =>
      string(32) "000000006cb064d90000000117a0144d"
      public $class =>
      string(10) "Ray\Di\Log"
      public $args =>
      array(0) {
      }
      public $instance =>
      NULL
      public $setters =>
      array(0) {
      }
      private $providerRef =>
      NULL
      private $logger =>
              ...

    }
    '000000006cb064dd0000000117a0144d' =>
    class Ray\Di\DependencyFactory#168 (7) {
      public $hash =>
      string(32) "000000006cb064dd0000000117a0144d"
      public $class =>
      string(21) "Ray\Di\WriterProvider"
      public $args =>
      array(0) {
      }
      public $instance =>
      NULL
      public $setters =>
      array(0) {
      }
      private $providerRef =>
      NULL
      private $logger =>
              ...

    }
    '000000006cb064c50000000117a0144d' =>
    class Ray\Di\DependencyFactory#167 (7) {
      public $hash =>
      string(32) "000000006cb064c50000000117a0144d"
      public $class =>
      string(13) "Ray\Di\Writer"
      public $args =>
      array(0) {
      }
      public $instance =>
      NULL
      public $setters =>
      array(0) {
      }
      private $providerRef =>
      NULL
      private $logger =>
              ...

    }
    '000000006cb064d40000000117a0144d' =>
    class Ray\Di\DependencyFactory#184 (7) {
      public $hash =>
      string(32) "000000006cb064d40000000117a0144d"
      public $class =>
      string(10) "Ray\Di\Log"
      public $args =>
      array(0) {
      }
      public $instance =>
      NULL
      public $setters =>
      array(0) {
      }
      private $providerRef =>
      NULL
      private $logger =>
              ...

    }
    '000000006cb064e60000000117a0144d' =>
    class Ray\Di\DependencyFactory#155 (7) {
      public $hash =>
      string(32) "000000006cb064e60000000117a0144d"
      public $class =>
      string(9) "Ray\Di\Db"
      public $args =>
      array(1) {
        [0] =>
        string(6) "my dsn"
      }
      public $instance =>
      NULL
      public $setters =>
      array(1) {
        'setLog' =>
        array(1) {
          [0] =>
          class Ray\Di\InstanceRef#156 (1) {
            public $refIndex =>
            string(32) "000000006cb064d40000000117a0144d"
          }
        }
      }
      private $providerRef =>
      NULL
      private $logger =>
              ...

    }
    '000000006cb064e10000000117a0144d' =>
    class Ray\Di\DependencyFactory#149 (7) {
      public $hash =>
      string(32) "000000006cb064e10000000117a0144d"
      public $class =>
      string(12) "Ray\Di\Diary"
      public $args =>
      array(3) {
        [0] =>
        class Ray\Di\InstanceRef#158 (1) {
          public $refIndex =>
          string(32) "000000006cb064d90000000117a0144d"
        }
        [1] =>
        class Ray\Di\InstanceRef#151 (1) {
          public $refIndex =>
          string(32) "000000006cb064c50000000117a0144d"
        }
        [2] =>
        class Ray\Di\InstanceRef#150 (1) {
          public $refIndex =>
          string(32) "000000006cb064e60000000117a0144d"
        }
      }
```

**Comment by koriym** [comment]
An AOP supported with 0206cd7 commit.

The limitation is same. You can't create objects(interceptors) in `Module` with `new` keyword, Because Ray.Di can not track instance creation (dependency resolution).

To instantiate interceptors, Please use `requestInjection()` even interceptor has no dependencies.

**OK**

``` php
        $diaryInterceptor = $this->requestInjection('Ray\Di\DiaryInterceptor');
        $this->bindInterceptor(
            $this->matcher->subclassesOf('Ray\Di\Diary'),
            $this->matcher->any(),
            [$diaryInterceptor]
        );
```

**NG**

``` php
        $this->bindInterceptor(
            $this->matcher->subclassesOf('Ray\Di\Diary'),
            $this->matcher->any(),
            [new \Ray\Di\DiaryInterceptor]
        );
```

**Comment by koriym** [comment]
@craigjbass [DependencyFactory](https://github.com/koriym/Ray.Di/blob/feature/di-compiler/src/DependencyFactory.php) is basically same idea as we mentioned earlier at #43
But It handles depdendencies resolution with minimum cost with optimised dependency graph data.

**Comment by koriym** [comment]
It is not auto generated class. But I think it is possible to do for further performance boost.

**Comment by koriym** [comment]
Here is the example with new `DiCompiler::create()` method.

``` php
$injectorFactory = function(){
    return Injector::create([new DiaryAopModule]);
};
// cache create
$cache = new FilesystemCache(__DIR__ . '/tmp');
$injector = DiCompiler::create($injectorFactory, $cache, 'CacheKey');
$injector->getInstance('Ray\Di\DiaryInterface');
// cache read
$injector = DiCompiler::create($injectorFactory, $cache, 'CacheKey');
$instance = $injector->getInstance('Ray\Di\DiaryInterface');
```

In first attempt `DiCompiler` collect dependency graph data which contains  constructor arguments, setter method names, setter method arguments, @PostConstruct method name, interceptors, and all object references from instance creation log in `Injector`.

In second request  DI compiler can inject with minimum cost without `Injector` and `Module`.

**Comment by koriym** [comment]
move to #56
