### ISSUE TITLE
Di Compiler

### ISSUE THREAD

**Issue by koriym** [ray-di/Ray.Di#56]
Here is the how to use di compiler.

``` php
$cache = new ApcCache;
$cacheKey = 'context-key';
$tmpDir = '/tmp';
$moduleProvider = function() {
    return new DiaryAopModule;
};
$injector = DiCompiler::create($moduleProvider, $cache, $cacheKey, $tmpDir);
$injector->getInstance('Ray\Di\DiaryInterface');
```

DiCompiler's logger stored all necessary information to instantiate object graph such as  constructor arguments, setter method and its arguments, init method, interceptors and  on each **Inject** request.

Then Di compiler **compile** object with injection log without injector or binding module.

Please check the performance. **It's fast.**

**Comment by koriym** [comment]
@mackstar Would you mind translate README.ja.md to README.md ? I add this section https://github.com/koriym/Ray.Di/commit/a86c92457ed6e48882e3f40b5b664f3e0546c0a2

**Comment by koriym** [comment]
@craigjbass I would like to hear your comment. We still have a room to boost the performance by class code generation of factory class.

**Comment by mackstar** [comment]
@koriym No problem...

**Comment by koriym** [comment]
@mackstar thanks ! :+1:

**Comment by koriym** [comment]
@mackstar or other native English speaker,  if you can name class more properly .Please give me a PR !
- **DiCompiler** compile object as injector did (but another way with speed)
- **DependencyFactory** - generic factory class
- **DependencyRefference** generic _pointer_ for dependency
- **CompileLogger** log and holds data for instance creation.

**Comment by craigjbass** [comment]
Interesting!

_DiCompiler_ 
_DependencyFactory_ 
_ReferenceContainer_ A container for references? That happen to be dependencies?
_DiGraphDataContainer_ A container for the DI graph data?

**Comment by craigjbass** [comment]
I will need to try this out -- but current very busy with some other projects. Very excited

**Comment by koriym** [comment]
**An example dependency resolution**
- `classMap` in **logger** holds the **[DependencyFactory](https://github.com/koriym/Ray.Di/blob/95669630080f371b218f16072063e8856ce25493/src/DependencyFactory.php)** id  (53) for interfface **Ray\Di\DiaryInterface**
- DependencyFactory 53 in holds class name   `Ray_Di_Diary_7fb772ec82de352322b146177262881cRayAop` and its 3 constructor arguments  as **[DependencyRefference](https://github.com/koriym/Ray.Di/blob/develop/src/DependencyReference.php)**. 
- First **DependencyRefference** holds **DependencyFactory** id 50, ok let's make instance 50
- **DependencyFactory** id 50 has class name but no dependencies ,  we can create instance with `new` operator.
- (If some other DependencyRefference points id 50, it already holds `instance`, behave as **singleton**.)
- _continued to second argument..._ till all dependencies are ready
- done ! Now we can instantiate `Ray_Di_Diary_7fb772ec82de352322b146177262881cRayAop` class.

and some other post instance creation process...
- if it has **interceptor(s)**, resolve dependency resolution for interceptors same way and bind it.
- **@PostConstuct** method invocation

![dependency resolution](https://f.cloud.github.com/assets/529021/2519724/1c934df0-b478-11e3-8cc5-dae527c10803.png)

**Comment by koriym** [comment]
- **logger**にある `classMap` が **Ray\Di\DiaryInterface**の**[DependencyFactory](https://github.com/koriym/Ray.Di/blob/95669630080f371b218f16072063e8856ce25493/src/DependencyFactory.php)** id  53を保持しています。 
- DependencyFactory 53 は インスタンスを生成するために `Ray_Di_Diary_7fb772ec82de352322b146177262881cRayAop`というクラス名と3つのコンストラクタ引き数を **[DependencyRefference](https://github.com/koriym/Ray.Di/blob/develop/src/DependencyReference.php)** として保持しています。DependencyRefferenceはDependencyFactoryのIDを保持しています. 
- 最初の **DependencyRefference** は **DependencyFactory** id 50を指しています。id 50のDependencyFactoryでインスタンスを作ります。
- **DependencyFactory** id 50 はクラス名を保持していますが依存はありません。`new` 演算子でインスタンスをつくることができます。
- (もし他のDependencyRefferenceがid 50を指していたら `instance`プロパティに格納されているのでシングルトンとして振る舞います)
- _二番目の引き数と続き..._ 全ての依存を解決します。
- できました ! `Ray_Di_Diary_7fb772ec82de352322b146177262881cRayAop` クラスをインスタンスにすることができます。

インスタンス生成後には...
- もし**インターセプター**があればインターセプターの依存解決を同様に行い、インスタンスに束縛します。
- **@PostConstuct** メソッドを実行します。
