### ISSUE TITLE
Interceptors are not called for setter injection at run-time but called at compile-time 

### ISSUE THREAD

**Issue by iteman** [ray-di/Ray.Di#75]
`@Inject` に合わせて独自のアノテーションを記述したセッターに対してインターセプターを呼び出すことができないかと試していた際に気がついたことを記述します。

まずモジュールコードは以下のようなものです。

``` php
$this->bindInterceptor(
    $this->matcher->any(),
    $this->matcher->logicalAnd(
        $this->matcher->annotatedWith('...\Baz')
        $this->matcher->annotatedWith('Ray\Di\Di\Inject'),
    ),
    [$this->requestInjection('...')]
);
```

クライアントコードは以下のようなものです。

``` php
/**
 * @Inject
 * @Baz
 */
public function setFoo(Bar $bar)
{
    ...
}
```

これを実行すると、バインディングタイムにより異なる振る舞いを示すことがわかりました。
1. コンパイルタイム - オブジェクト作成時にユーザーのインターセプターが呼び出される。意図した振る舞い。
2. ランタイム - オブジェクト作成時にユーザーのインターセプターは呼び出されない。意図しない振る舞い。

私の調べた範囲では、以下のことが原因らしいとわかりました。
1. コンパイルタイム: [Injector::getInstance()](https://github.com/koriym/Ray.Di/blob/163d4d467cc209db709ec5a6a5949bfc254e2a47/src/Injector.php#L200-L244) のセッターが呼ばれる前にアスペクトが織り込まれているため、オブジェクト作成時にユーザーのインターセプターが呼び出される。
2. ランタイム: [DependencyFactory::get()](https://github.com/koriym/Ray.Di/blob/163d4d467cc209db709ec5a6a5949bfc254e2a47/src/DependencyFactory.php#L91-L116) では、先にセッターが呼ばれインターセプターはあとで織り込まれるため、オブジェクト作成時にユーザーのインターセプターは呼び出されない。

質問は以下のとおりです。
1. コンパイルタイムおよびランタイムで振る舞いが異なるのは仕様かどうか？
2. 仕様でない（バインディングタイムによらず同じ振る舞いが仕様である）場合、以下のいずれが正しいのか？
   - インジェクション時にインターセプター呼び出しを行う
   - インジェクション時にインターセプター呼び出しを行わない

**Comment by koriym** [comment]
これは`DiCompiler`を使用したときだけの問題でしょうか？

**Comment by iteman** [comment]
`DiCompiler` を使ったものでしか確認できていませんので、他の方法でどうなるかはわかりません。

**Comment by koriym** [comment]
`DiCompiler`だけの問題だと思います。

**Comment by koriym** [comment]
> コンパイルタイムおよびランタイムで振る舞いが異なるのは仕様かどうか？

= `Injector`と`Compiler`でインターセプターの適用のタイミングが違うのは仕様か？

仕様ではありません。

> インジェクション時にインターセプター呼び出し

セッターメソッドにインターセプターが適用されるか？ということでしたら、これは想定してなかった利用です。どうするかを考えないといけません。

**Comment by iteman** [comment]
ありがとうございます。現在の仕様について理解いたしました。

**Comment by koriym** [comment]
こちらこそありがとうございます。

> セッターメソッドにインターセプターが適用されるか？

@iteman さん、これどうすべきと考えますか？意見を聞きたいです。

**Comment by iteman** [comment]
> > セッターメソッドにインターセプターが適用されるか？
> 
> @iteman さん、これどうすべきと考えますか？意見を聞きたいです。

現在の仕様は `@Inject` 以外のメソッド呼び出しによってのみインターセプターが適用されるので `@Inject` が例外扱いになっています。ユーザーによるメソッド呼び出しまたは BEAR.Resource の `onGet()` 等の自動的な呼び出しに対してフックされている。セッターメソッドおよびコンストラクターによるインジェクションを適用対象にすると一貫性はあります。しかし、有用なユースケースが見つかるまでは現状のままでいいのではないかと思います。

私がやりたかったのは、以下のようなクライアントコードによって、指定コンテキストに応じた `Doctrile\DBAL\Connection` オブジェクトをセッターメソッドに与えることでした。

``` php
...
use Doctrine\DBAL\Connection;
...
class Foo
{
    /**
     * @Inject
     * @PersistenceContext("write")
     */
    public function setConnection(Connection $connection)
    {
        $this->connection = $connection;
    }
    ...
```

しかし、（`toCallable()` を使うことで）実際に試してみると、元の引数にダミーオブジェクトが渡るように設定しないといけないことがわかり、トリックを作るための半ば無駄なコードを書かなくてはならない点で良いものにはなりませんでした。以前の別の場所でのやりとりの際に出たものだと思いますが、上記のコードの場合のより望ましいプロセスは以下のようなものと考えます。
1. Foo オブジェクトが要求される
2. setConnection() の引数 Connection オブジェクトの作成を `toProvider()` で指定された `ProviderInterface` オブジェクトに移譲する
3. `ProviderInterface` オブジェクトは `MethodInterceptor::invoke()` の引数と同じように `MethodInvocation` オブジェクトにアクセスできる

長々と書いてしまいましたが、私の意見は以下のとおりです。
- `@Inject` によるセッターメソッドおよびコンストラクター呼び出しに対するインターセプターの適用は行わない（コンパイルタイムで適用されてしまう問題は修正する）。
- `toProvdier` で Foo::setConnection() の `MethodInvocation` オブジェクトにアクセスできるようにする

**Comment by koriym** [comment]
@iteman ありがとうございます。

> @Inject によるセッターメソッドおよびコンストラクター呼び出しに対するインターセプターの適用は行わない（コンパイルタイムで適用されてしまう問題は修正する）。

修正しました。

> toProvdier で Foo::setConnection() の MethodInvocation オブジェクトにアクセスできるようにする

これなのですが、通常は`setConnection()`が呼ばれるのはオブジェクトの生成時なのでメソッド実行時の`MethodInvocation`にアクセスできません。依存解決をメソッド実行時に行うインターセプターを用意して、という方向で検討してみます。

**Comment by iteman** [comment]
> > `toProvdier` で Foo::setConnection() の `MethodInvocation` オブジェクトにアクセスできるようにする
> 
> これなのですが、通常はsetConnection()が呼ばれるのはオブジェクトの生成時なのでメソッド実行時のMethodInvocationにアクセスできません。依存解決をメソッド実行時に行うインターセプターを用意して、という方向で検討してみます。

すみません、`MethodInvocation` は私の勘違いでした。`@Inject` が定義されているメソッドの静的な情報（例えば `ReflectionMethod`、クラス名とメソッド名）が参照できればコンパイルタイム（`DependencyFactory::get()` 実行時） に解決できると思うのですがいかがでしょうか。ここで setConnection() は依存解決時に自動的に呼ばれることを想定しています。

**Comment by iteman** [comment]
> > `@Inject` によるセッターメソッドおよびコンストラクター呼び出しに対するインターセプターの適用は行わない（コンパイルタイムで適用されてしまう問題は修正する）。
> 
> 修正しました。

@koriym ありがとうございます！

**Comment by koriym** [comment]
`MethodInvocation`は メソッドによって`master` / `slave`を判別して生成する`DbInjector`などに使えるのではないかと思いました。

> `@Inject` が定義されているメソッドの静的な情報（例えば `ReflectionMethod`、クラス名とメソッド名）が参照できればコンパイルタイム（`DependencyFactory::get()` 実行時） に解決できると思うのですがいかがでしょうか。

これはどのような時に必要でしょうか？`@Named`では解決できないでしょうか？

**Comment by iteman** [comment]
> MethodInvocationは メソッドによってmaster / slaveを判別して生成するDbInjectorなどに使えるのではないかと思いました。
> 
> > @Inject が定義されているメソッドの静的な情報（例えば ReflectionMethod、クラス名とメソッド名）が参照できればコンパイルタイム（DependencyFactory::get() 実行時） に解決できると思うのですがいかがでしょうか。
> 
> これはどのような時に必要でしょうか？@Namedでは解決できないでしょうか？

BEAR ではとても簡単にアノテーションを作成できるので、それをより活かしたいと考えています。

もちろん `@Named` でも解決できますが、以下のように明示的に任意のアノテーションを使えるのが希望です。`@Named` のような `@Inject` 連動のアノテーションをユーザーが作成することを可能にする機能といえますね。

```
/**
 * @Inject
 * @PersistentenceContext("slave")
 */
public function setConnection(Connection $connection)
{
    $this->connection = $connection;
}
```

**Comment by koriym** [comment]
分かりました！`@Named`と同等の機能であれば、これは経緯があって`Guice`で採用されている任意のアノテーションを用意するバインディングを省略して`@Named`にしているだけなのです。

なのでこの提案は`Guice`と同じように任意のアノテーションを`Named Binding`に使えるようにするという提案ですね。

**Comment by koriym** [comment]
``` php
/**
 * @Inject
 * @Named("right")
 */
public function setLeg(LegInterface $rightLeg)
{
```

の代わりに

``` php
/**
 * @Inject
 * @Right
 */
public function setLeg(LegInterface $rightLeg)
{
```

という風に

**Comment by iteman** [comment]
はい、その通りです。

**Comment by koriym** [comment]
``` php
/**
 * @Inject
 * @Right("rightLeg")
 * @Left("leftLeg")
 */
public function setLeg(LegInterface $rightLeg, LegInterface $leftLeg)
{
```

複数のパラメーターだとこんな感じでしょうか

**Comment by iteman** [comment]
はい。

一つ気になるのは、現在の `@Named` のように固定で値を設定しておくのではなく、`toProvider` が呼び出される必要がある点です。

**Comment by koriym** [comment]
> 現在の @Named のように固定で値を設定しておくではなく、toProvider が呼び出される必要がある点です。

もう少し詳しく説明してもらっていいですか。

**Comment by iteman** [comment]
以下のようなユースケースを考えています。

モジュールコード:

``` php
class ...Module exnteds AbstractModule
{
    protected function configure()
    {
        // 1 つのアノテーションを指定、アノテーションの値はプロバイダーで取得可能。コンストラクタ・セッターメソッドのその他のアノテーションにもアクセスしたい場合はどうする？
        $this->bind('Doctrine\DBAL\Connection')->annotatedWith('PersistenceContext')->toProvider('\Foo\Bar\ConnectionProvider');
        // または単に Provider で一つ以上のアノテーションおよび値にアクセス可能
        $this->bind('Doctrine\DBAL\Connection')->toProvider('\Foo\Bar\ConnectionProvider');
```

クライアントコード:

``` php
use Doctrine\DBAL\Connection;
class ...
{
    /**
     * @Inject
     * @PersistenceContext("write")
     */
    public function setConnection(Connection $connection)
    {
        $this->connection = $connection;
    }
```

**Comment by koriym** [comment]
アノテーションの値を`Provider`で利用するということですね。

**Comment by iteman** [comment]
はい、そうです。

**Comment by koriym** [comment]
@iteman 根本的な問題は`Ray.Di`の複雑さにあって、そういう機能を実現したいときに今の実装を理解して自分の行いたいものに変更する事が難しいのではないかと考えました。

**Comment by koriym** [comment]
@iteman コンパチビリティを保ちながら新しいものに書き直そうと考えていて、すでに着手しています。このissueはそのバージョンで対応しようと思います。

**Comment by iteman** [comment]
@koriym ありがとうございます。楽しみにしています。

**Comment by koriym** [comment]
一旦閉じますー

**Comment by koriym** [comment]
0f4848052d0027908d5a283fb39d7b62aea85397 でアノテーションによる`Named Binding`が可能になりました。

**Comment by koriym** [comment]
[#83]のように使います。

**Comment by iteman** [comment]
@koriym ありがとうございます。早速試してみたいと思います。

**Comment by koriym** [comment]
更に#104 CDI (Context and Dependency Injection) で対応を進めました。InjectionPointのリフレクションやアノテーションの値を元に依存を決定できるようになりました。
