### ISSUE TITLE
Cannot use Scope::SINGLETON for named bindings

### ISSUE THREAD

**Issue by lorenzo** [ray-di/Ray.Di#82]
When having more than one named binding for the same interface, it is not possible to use `->in(Scope::SINGLETON)` as all instances of the interface will be of the same type regardless of the name tag.

Example:

``` php
@Inject
@Named("a=first")
public function setStuff(ThingInterface $a) { ... }

@Inject
@Named("a=second")
public function setOtherStuff(ThingInterface $a) { ... }
```

And in a module bind like this:

``` php
$this->bind('ThingInterface')->annotatedWith('first')->to($class)->in(Scope::SINGLETON);
$this->bind('ThingInterface')->annotatedWith('second')->to($class)->in(Scope::SINGLETON);
```

When instantiating though the injector the class containing the setters, both methods will receive the class annotated with `first`.

This used to work correctly in version `1.2` but broken after updating to `1.4`

**Comment by lorenzo** [comment]
The commit where the problem starts is 04881f79fb80981be1d6bf209a7e3b903e42328b

**Comment by jippi** [comment]
:+1:

**Comment by ankr** [comment]
:+1:

**Comment by koriym** [comment]
@lorenzo Thank for the report and specify the commit  when the problem started.

**Comment by koriym** [comment]
@lorenzo Would you mind try a955497 (latest develop) ? Hope it fix this issue.

**Comment by lorenzo** [comment]
yes, will do

**Comment by lorenzo** [comment]
@koriym works perfectly, good job!

**Comment by ankr** [comment]
:+1: nice

**Comment by koriym** [comment]
published as [1.4.5](https://github.com/koriym/Ray.Di/releases/tag/1.4.5)
thanks !

**Comment by lorenzo** [comment]
Thank you for fixing it so fast :)

**Comment by koriym** [comment]
you are welcome @lorenzo. Thank you for using Ray.Di.

**Comment by koriym** [comment]
The next version of Ray.Di is coming soon. Full ( include test) code are rewritten for the performance and quality.

**About Performance**:  I pushed benchmark https://github.com/koriym/php-dependency-injection-benchmarks (made by @TomBZombie).  It's roughly more than 5 times faster than Symfony-Di / PHP-Di. A bit slower than Aura.Di (but you know architecture is very different). (I feel there are some room to improve but satisfactory as a start.)

**About Quality:**: Statical code analysts tools (phpmd, pdepend, or scrutinizer-ci) are showing kind of highest score now but off course it's only judged by machine, I need code review by software experts like you or @mackstar to push `Ray.Di` next level.

It's nice to have your feedback or code review when you have a time. would love to hear your needs or dissatisfaction. Thanks again using Ray.Di @lorenzo @ankr @jippi

**Comment by lorenzo** [comment]
@koriym I will take a look during the weekend!

**Comment by koriym** [comment]
Muchas gracias mi amigo !
