### ISSUE TITLE
PHP 5.4 Support

### ISSUE THREAD

**Issue by jamolkhon** [ray-di/Ray.Di#86]
Next major release (2.0+) requires PHP 5.5. It seems, the only new feature of PHP 5.5 you're using is the [Class name resolution via ::class](http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name) in a few places (I counted 5) under src, and everywhere under tests/docs. Can we get PHP 5.4 support back please? :)

**Comment by koriym** [comment]
What about PHP 5.4 support back for `/src` but not for `/tests` ? You can use PHP5.4 enviroment, but develop at PHP 5.5+.

**Comment by jamolkhon** [comment]
Good enough, thanks :)

**Comment by koriym** [comment]
If you send a pull-request I will be happy to merge it.

**Comment by jamolkhon** [comment]
#88
