### ISSUE TITLE
Interface names

### ISSUE THREAD

**Issue by jamolkhon** [ray-di/Ray.Di#87]
I think it would be better if interfaces didn't have the `Interface` suffix like `ProviderInterface`. I think they should be simple, like `Provider`. I see two reasons for having the `Interface` suffix.
1. To show that it's really an interface (why?)
2. To reserve the short name for the (default) implementation
Most of the time we work with the interface. The implementation class is used rarely, ideally once when binding:

```
$this->bind(Finder::class)->to(DefaultFinder::class);
```

instead of:

```
$this->bind(FinderInterface::class)->to(Finder::class);
```

**Comment by koriym** [comment]
Hi @jamolkhon 

I think a lot of similar discussions are seen on the Web. 
http://www.reddit.com/r/PHP/comments/2kk4v2/naming_interfaces_in_php_or_why_you_shouldnt_use/

I can understand your point, I like the comment by ircmaxell in this thread, and I also like the entry by mathias verraes.
http://verraes.net/2013/09/sensible-interfaces/

Actually this project also started without `Interface` suffix.
.... But I changed my mind. Marco Pivetta exactly expressed what I thought myself at that time..

See the many comments in these thread. Skilled developer has different opinion. I thought this is not simple issue, One single best practice is not shared. That's the reason `PSR-2` intentionally not defined about this name convention, I think

Then I conclude to follow simplest way as many frameworks chose.

**Comment by koriym** [comment]
@jamolkhon

What about adding alias interface `Provider` for `ProviderInterface` ? 8ef5dbf83902e0b8b7b6ea6a406ef1eeed79b7c8
User can have a consistency in their application code no matter which name convention they have (prefer).

**Comment by jamolkhon** [comment]
:+1:
