### ISSUE TITLE
Cannot get latest version with composer

### ISSUE THREAD

**Issue by akkie** [ray-di/Ray.Di#9]
Hi,

I cannot get the dev-master branch through composer. It installs always the 1.0.0.-beta1 tag. I have tested this with a clean composer.json.

``` json
{
    "require": {
        "ray/di": "dev-master"
    },
    "minimum-stability": "dev"
}
```

Installing dependencies
- Installing doctrine/common (2.3.x-dev bb0aebb)
  Cloning bb0aebbf234db52df476a2b473d434745b34221c
- Installing ray/aop (dev-master 2d118d3)
  Cloning 2d118d33454a2c2006b83a2d62ae9270eea33413
- Installing aura/di (dev-master 8730acf)
  Cloning 8730acf19625fb74fca9f5ec8a0f80012c754442
- Installing ray/di (dev-master 1.0.0-beta1)
  Cloning 1.0.0-beta1

Cheers,
Christian

**Comment by koriym** [comment]
Confirmed. But I'm not sure what I should do now. Take a little to time to find it.

**Comment by akkie** [comment]
I have created a thread about this issue in the composer newsgroup.

https://groups.google.com/forum/?hl=de&fromgroups=#!topic/composer-dev/4OsQoQWJ6sU

**Comment by koriym** [comment]
Good job, Christian ! hope to have an answer shortly.

**Comment by koriym** [comment]
Thanks Christian.
https://github.com/composer/packagist/issues/186#issuecomment-8767684
